"""empty message

Revision ID: 3055d7942c23
Revises: 5c7cb8528aba
Create Date: 2023-05-09 22:22:23.603426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3055d7942c23'
down_revision = '5c7cb8528aba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_phrases',
    sa.Column('saved_phrases_id', sa.Integer(), nullable=False),
    sa.Column('saved_phrases', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('saved_phrases_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved_phrases')
    # ### end Alembic commands ###
