"""empty message

Revision ID: 32b8e2efd212
Revises: 732317be665a
Create Date: 2023-05-12 17:39:16.471724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32b8e2efd212'
down_revision = '732317be665a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('censored_terms',
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('term', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('term_id')
    )
    with op.batch_alter_table('censored_terms', schema=None) as batch_op:
        batch_op.create_index('cw_idx', ['term_id'], unique=False)

    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.drop_index('posidx')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.create_index('posidx', ['partofspeech'], unique=False)

    with op.batch_alter_table('censored_terms', schema=None) as batch_op:
        batch_op.drop_index('cw_idx')

    op.drop_table('censored_terms')
    # ### end Alembic commands ###
