"""empty message

Revision ID: 6a161b6a258a
Revises: 3055d7942c23
Create Date: 2023-05-09 22:31:13.295504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a161b6a258a'
down_revision = '3055d7942c23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_phrases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_phrases', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
