"""empty message

Revision ID: 71ae62992256
Revises: 2eade073bf40
Create Date: 2023-05-11 17:38:12.925027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71ae62992256'
down_revision = '2eade073bf40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_phrases', schema=None) as batch_op:
        batch_op.alter_column('saved_phrases',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=80),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_phrases', schema=None) as batch_op:
        batch_op.alter_column('saved_phrases',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=40),
               existing_nullable=True)

    # ### end Alembic commands ###
