"""empty message

Revision ID: 732317be665a
Revises: 9212652403fd
Create Date: 2023-05-12 12:27:53.725500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '732317be665a'
down_revision = '9212652403fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.drop_column('symbol_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.add_column(sa.Column('symbol_id', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
