"""empty message

Revision ID: 76f191d2d346
Revises: 29ab8782ebd0
Create Date: 2023-05-06 18:06:40.939418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76f191d2d346'
down_revision = '29ab8782ebd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.alter_column('word',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('partofspeech',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.alter_column('partofspeech',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('word',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###
