"""empty message

Revision ID: 7c18e26a090f
Revises: 9098bba505a2
Create Date: 2023-04-02 16:39:51.822580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c18e26a090f'
down_revision = '9098bba505a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plural', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tile', schema=None) as batch_op:
        batch_op.drop_column('plural')

    # ### end Alembic commands ###
