"""empty message

Revision ID: 85348b9ac3ec
Revises: 6a161b6a258a
Create Date: 2023-05-10 14:29:50.954393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85348b9ac3ec'
down_revision = '6a161b6a258a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.add_column(sa.Column('symbol', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.drop_column('symbol')

    # ### end Alembic commands ###
