"""empty message

Revision ID: 9212652403fd
Revises: 71ae62992256
Create Date: 2023-05-12 11:09:52.123235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9212652403fd'
down_revision = '71ae62992256'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade_level', sa.String(length=20), nullable=True))
        batch_op.drop_column('sub_category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sub_category', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.drop_column('grade_level')

    # ### end Alembic commands ###
