"""empty message

Revision ID: 9bbfe33d6a11
Revises: 9f96d0357b2b
Create Date: 2023-05-10 23:11:51.676564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bbfe33d6a11'
down_revision = '9f96d0357b2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.create_index('posidx', ['partofspeech'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.drop_index('posidx')

    # ### end Alembic commands ###
