"""empty message

Revision ID: 9f96d0357b2b
Revises: 85348b9ac3ec
Create Date: 2023-05-10 18:05:58.793444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f96d0357b2b'
down_revision = '85348b9ac3ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.create_index('idx', ['word_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.drop_index('idx')

    # ### end Alembic commands ###
