"""empty message

Revision ID: a84df409e6a1
Revises: 32b8e2efd212
Create Date: 2023-05-14 20:41:09.688434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a84df409e6a1'
down_revision = '32b8e2efd212'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_phrases', schema=None) as batch_op:
        batch_op.alter_column('saved_phrases',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_phrases', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('saved_phrases',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)

    # ### end Alembic commands ###
