"""empty message

Revision ID: a9488373b214
Revises: 2fdad3374598
Create Date: 2023-03-25 21:34:40.265633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9488373b214'
down_revision = '2fdad3374598'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('partofspeech', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tile', schema=None) as batch_op:
        batch_op.drop_column('partofspeech')

    # ### end Alembic commands ###
