"""empty message

Revision ID: b3e3a0fa055d
Revises: 9f96d0357b2b
Create Date: 2023-05-11 01:18:23.957372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3e3a0fa055d'
down_revision = '9f96d0357b2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pinned_words',
    sa.Column('pinnedwords_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('pinnedwords_id')
    )
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.create_index('posidx', ['partofspeech'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.drop_index('posidx')

    op.drop_table('pinned_words')
    # ### end Alembic commands ###
