"""empty message

Revision ID: e0d7fcc65407
Revises: ebde70f0fbb3
Create Date: 2023-05-02 18:27:59.906615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0d7fcc65407'
down_revision = 'ebde70f0fbb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adjectives', schema=None) as batch_op:
        batch_op.drop_constraint('adjectives_pos_id_fkey', type_='foreignkey')

    with op.batch_alter_table('nouns', schema=None) as batch_op:
        batch_op.drop_constraint('nouns_pos_id_fkey', type_='foreignkey')

    with op.batch_alter_table('verbs', schema=None) as batch_op:
        batch_op.drop_constraint('verbs_pos_id_fkey', type_='foreignkey')

    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.drop_constraint('words_symbol_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('words_partofspeech_fkey', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.create_foreign_key('words_partofspeech_fkey', 'partsof_speech', ['partofspeech'], ['partofspeech_id'])
        batch_op.create_foreign_key('words_symbol_id_fkey', 'symbols', ['symbol_id'], ['symbol_id'])

    with op.batch_alter_table('verbs', schema=None) as batch_op:
        batch_op.create_foreign_key('verbs_pos_id_fkey', 'partsof_speech', ['pos_id'], ['partofspeech_id'])

    with op.batch_alter_table('nouns', schema=None) as batch_op:
        batch_op.create_foreign_key('nouns_pos_id_fkey', 'partsof_speech', ['pos_id'], ['partofspeech_id'])

    with op.batch_alter_table('adjectives', schema=None) as batch_op:
        batch_op.create_foreign_key('adjectives_pos_id_fkey', 'partsof_speech', ['pos_id'], ['partofspeech_id'])

    # ### end Alembic commands ###
